CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT, role TEXT, visible INTEGER);
CREATE TABLE islands (id SERIAL PRIMARY KEY, islandname TEXT, userid INTEGER, visible INTEGER);
CREATE TABLE outfits (id SERIAL PRIMARY KEY, outfitname TEXT, visible INTEGER);
CREATE TABLE species (id SERIAL PRIMARY KEY, speciesname TEXT, visible INTEGER);
CREATE TABLE personalities (id SERIAL PRIMARY KEY, personalityname TEXT, visible INTEGER);
CREATE TABLE characters (id SERIAL PRIMARY KEY, charactername TEXT, speciesid INTEGER, personalityid INTEGER, outfitid INTEGER,  birthmmdd INTEGER, visible INTEGER);
CREATE TABLE characteronisland (islandid INTEGER, characterid INTEGER, outfitid INTEGER, visible INTEGER);
INSERT INTO personalities (personalityname, visible) VALUES ('Normal', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Peppy', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Snooty', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Sisterly', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Lazy', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Jock', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Cranky', 1);
INSERT INTO personalities (personalityname, visible) VALUES ('Smug', 1);
INSERT INTO species (speciesname, visible) VALUES ('Dog', 1);
INSERT INTO species (speciesname, visible) VALUES ('Cat', 1);
INSERT INTO species (speciesname, visible) VALUES ('Bird', 1);
INSERT INTO species (speciesname, visible) VALUES ('Rabbit', 1);
INSERT INTO species (speciesname, visible) VALUES ('Horse', 1);
INSERT INTO species (speciesname, visible) VALUES ('Penguin', 1);
INSERT INTO species (speciesname, visible) VALUES ('Cow', 1);
INSERT INTO species (speciesname, visible) VALUES ('Hamster', 1);
INSERT INTO species (speciesname, visible) VALUES ('Octopus', 1);
INSERT INTO outfits (outfitname, visible) VALUES ('Suit', 1);
INSERT INTO outfits (outfitname, visible) VALUES ('Polka dot dress', 1);
INSERT INTO outfits (outfitname, visible) VALUES ('Natural dress', 1);
INSERT INTO outfits (outfitname, visible) VALUES ('Dog suit', 1);
INSERT INTO outfits (outfitname, visible) VALUES ('Sporty t-shirt', 1);
INSERT INTO characters (charactername, speciesid, personalityid, outfitid, birthmmdd, visible) VALUES ('Rosie', 2, 2, 2, 101, 1);
INSERT INTO characters (charactername, speciesid, personalityid, outfitid, birthmmdd, visible) VALUES ('Goldie', 1, 1, 3, 101, 1);
INSERT INTO characters (charactername, speciesid, personalityid, outfitid, birthmmdd, visible) VALUES ('Jay', 3, 6, 5, 101, 1);
INSERT INTO characters (charactername, speciesid, personalityid, outfitid, birthmmdd, visible) VALUES ('Octavian', 9, 7, 1, 101, 1);
